const MutationKeys = {
  SSH_KEYS: 'SSH_KEYS',
  VM_CREATION_REQUESTS: 'VM_CREATION_REQUESTS',
  VM_DELETION_REQUESTS: 'VM_DELETION_REQUESTS',
  VM_ARCHIVE_REQUESTS: 'VM_ARCHIVE_REQUESTS',
  DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',

  W_CREATE_CUSTOMER: 'W_CREATE_CUSTOMER',
  W_UPDATE_CUSTOMER: 'W_UPDATE_CUSTOMER',
  W_CREATE_PROJECT: 'W_CREATE_PROJECT',
  // W_CREATE_RESOURCE: 'W_ADD_RESOURCE',
  W_CREATE_SSH_KEY: 'W_CREATE_SSH_KEY',
  W_DELETE_SSH_KEY: 'W_DELETE_SSH_KEY',
}

export default MutationKeys
