const MutationKeys = {
  SSH_KEYS: 'SSH_KEYS',
  VM_CREATION_REQUESTS: 'VM_CREATION_REQUESTS',
  VM_DELETION_REQUESTS: 'VM_DELETION_REQUESTS',
  VM_ARCHIVE_REQUESTS: 'VM_ARCHIVE_REQUESTS',
  DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',
}

export default MutationKeys
