const QueryKeys = {
  MY_IP: 'MY_IP',
  SSH_KEYS: 'SSH_KEYS',
  VMS: 'VMS',
  VM: 'VM',
  VM_TEMPLATES: 'VM_TEMPLATES',
  VM_TEMPLATE: 'VM_TEMPLATE',
  TOKEN_FETCH_INFO: 'TOKEN_FETCH_INFO',
  VM_PROVIDERS: 'VM_PROVIDERS',
  VM_PROVIDER: 'VM_PROVIDER',

  W_CONFIGURATION: 'W_CONFIGURATION',
  W_CUSTOMERS: 'W_CUSTOMERS',
  W_CUSTOMER: 'W_CUSTOMER',
  W_CUSTOMER_USERS: 'W_CUSTOMER_USERS',
  W_PROJECTS: 'W_PROJECTS',
  // W_PROJECT: 'W_PROJECT',
  W_SSH_KEYS: 'W_SSH_KEYS',
  W_SSH_KEY: 'W_SSH_KEY',
  W_EVENTS: 'W_EVENTS',
  W_CUSTOMER_SERVICE_PROVIDER: 'W_CUSTOMER_SERVICE_PROVIDER',
  W_MARKETPLACE_OFFERINGS: 'W_MARKETPLACE_OFFERINGS',
  W_MARKETPLACE_CATEGORIES: 'W_MARKETPLACE_CATEGORIES',
  W_RESOURCES: 'W_RESOURCES',
  W_RESOURCE: 'W_RESOURCE',
  W_OPENSTACK_INSTANCE: 'W_OPENSTACK_INSTANCE',
  W_OPENSTACK_TENANT: 'W_OPENSTACK_TENANT',
  W_PLAN_DETAILS: 'W_PLAN_DETAILS',

  // Cost Policy keys (Phase 2)
  W_CUSTOMER_COST_POLICIES: 'W_CUSTOMER_COST_POLICIES',
  W_PROJECT_COST_POLICIES: 'W_PROJECT_COST_POLICIES',
  W_ORG_PROJECT_COST_POLICIES: 'W_ORG_PROJECT_COST_POLICIES',
  W_COST_POLICY_ACTIONS: 'W_COST_POLICY_ACTIONS',

  // Billing & Invoice keys
  W_INVOICE_TOTAL_PRICE: 'W_INVOICE_TOTAL_PRICE',
  W_INVOICE_ITEMS: 'W_INVOICE_ITEMS',
  W_PROJECT_COSTS: 'W_PROJECT_COSTS',
  W_CUSTOMER_COSTS: 'W_CUSTOMER_COSTS',
  W_TOTAL_PRICE: 'W_TOTAL_PRICE',
  W_INVOICE_ITEMS_COSTS: 'W_INVOICE_ITEMS_COSTS',
  W_ORG_PROJECT_COSTS: 'W_ORG_PROJECT_COSTS',

  // User Management keys (Phase 2)
  W_INVITATIONS: 'W_INVITATIONS',
  W_CUSTOMER_MEMBERS: 'W_CUSTOMER_MEMBERS',
  W_PROJECT_MEMBERS: 'W_PROJECT_MEMBERS',
  W_USER_SEARCH: 'W_USER_SEARCH',

  // Group Invitations & Permission Requests (Phase 2)
  W_GROUP_INVITATIONS: 'W_GROUP_INVITATIONS',
  W_PERMISSION_REQUESTS: 'W_PERMISSION_REQUESTS',
  W_MY_PERMISSION_REQUESTS: 'W_MY_PERMISSION_REQUESTS',

  // VM Orders (Phase 4)
  W_MARKETPLACE_ORDERS: 'W_MARKETPLACE_ORDERS',
  W_ORDER_DETAILS: 'W_ORDER_DETAILS',

  // OpenStack Resources (Phase 4)
  W_OPENSTACK_IMAGES: 'W_OPENSTACK_IMAGES',
  W_OPENSTACK_FLAVORS: 'W_OPENSTACK_FLAVORS',
  W_OPENSTACK_VOLUME_TYPES: 'W_OPENSTACK_VOLUME_TYPES',
  W_OPENSTACK_SUBNETS: 'W_OPENSTACK_SUBNETS',
  W_OPENSTACK_FLOATING_IPS: 'W_OPENSTACK_FLOATING_IPS',
  W_OPENSTACK_SECURITY_GROUPS: 'W_OPENSTACK_SECURITY_GROUPS',
}

export default QueryKeys
