const QueryKeys = {
  MY_IP: 'MY_IP',
  SSH_KEYS: 'SSH_KEYS',
  VMS: 'VMS',
  VM: 'VM',
  VM_TEMPLATES: 'VM_TEMPLATES',
  VM_TEMPLATE: 'VM_TEMPLATE',
  TOKEN_FETCH_INFO: 'TOKEN_FETCH_INFO',
  VM_PROVIDERS: 'VM_PROVIDERS',
  VM_PROVIDER: 'VM_PROVIDER',

  W_CONFIGURATION: 'W_CONFIGURATION',
  W_CUSTOMERS: 'W_CUSTOMERS',
  W_CUSTOMER: 'W_CUSTOMER',
  W_CUSTOMER_USERS: 'W_CUSTOMER_USERS',
  W_PROJECTS: 'W_PROJECTS',
  // W_PROJECT: 'W_PROJECT',
  W_SSH_KEYS: 'W_SSH_KEYS',
  W_SSH_KEY: 'W_SSH_KEY',
  W_EVENTS: 'W_EVENTS',
  W_CUSTOMER_SERVICE_PROVIDER: 'W_CUSTOMER_SERVICE_PROVIDER',
  W_MARKETPLACE_OFFERINGS: 'W_MARKETPLACE_OFFERINGS',
  W_MARKETPLACE_CATEGORIES: 'W_MARKETPLACE_CATEGORIES',
  W_RESOURCES: 'W_RESOURCES',
}

export default QueryKeys
