export { default as SelectOrganization } from './SelectOrganization'
export { default as CreateOrganization } from './CreateOrganization'
export { ViewOrganization } from './ViewOrganization'
export { default as EditOrganization } from './EditOrganization'
export { default as SelectProject } from './SelectProject'
export { default as CreateProject } from './CreateProject'
export { default as CreateTenant } from './CreateTenant'
export { default as TenantOrderStatus } from './TenantOrderStatus'
export { default as TenantDetails } from './TenantDetails'
export { default as CreateOffering } from './CreateOffering'
export { default as ViewEditOffering } from './ViewEditOffering'
export { default as TestPage } from './TestPage'
export { default as VmDashboard } from './VmDashboard'
export { default as UserVmDashboard } from './UserVmDashboard'
export { default as VmDetails } from './VmDetails'
export { default as CreateVm } from './CreateVm'

// Admin pages
export { default as CreateCostPolicy } from './admin/CreateCostPolicy'
export { default as EditCostPolicy } from './admin/EditCostPolicy'
