name: Deploy to Nginx

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build React App
      run: |
        echo "${{ secrets.DOT_ENV }}" > .env.production
        echo "${{ secrets.DOT_ENV_SENTRY }}" > .env.sentry-build-plugin
        yarn
        yarn build:prod

    - name: Deploy to Nginx
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/var/www/html"
